CREATE DATABASE DjezzyDB; 

CREATE TABLE usersDjezzy 
(id BIGSERIAL PRIMARY KEY NOT NULL,
firstname VARCHAR(200) NOT NULL,
lastname VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL,
password VARCHAR(200) NOT NULL,
UNIQUE(email));